package ar.edu.untref.aydoo;

public enum Provincia {
	
	JUJUY, SALTA, FORMOSA, CHACO, CATAMARCA, TUCUMAN, SANTIAGODELESTERO, CORRIENTES, MISIONES, LARIOJA, SANTAFE, SANJUAN, CORDOBA,
	ENTRERIOS, MENDOZA, SANLUIS, LAPAMPA, BUENOSAIRES, NEUQUEN, RIONEGRO, CHUBUT, SANTACRUZ, TIERRADELFUEGO
}
